# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 01e94ac1bf5fe68c76b406df29d6d1fbf0f2ac1ba1f7491475f0f3c43d7aa35280d125e007f471ca9aec83e0da491094b71f5b42a12cd71c047521970ce558b8

test:
  secret_key_base: 778ef050af2dc489dc8952fc482346ac00fd487fea46c1dc802ac9a9b1f0f8f988352dfe9e14556e362152d8ed85eacb4220155349ac9ba294b1378a5b2d8d5b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
